### ISSUE TITLE
scala presentation compiler

### ISSUE THREAD

**Issue by paulp** [flatmap/cobra#18]
Scala presentation compiler can only be accessed on designated thread. This crash is easily reproducible for me if I select a name in any nontrivial piece of code.

``````
        ____      _
       / ___|___ | |__  _ __ __ _ TM
      | |   / _ \| '_ \| '__/ _` |
      | |__| (_) | |_) | | | (_| |
       \____\___/|_.__/|_|  \__,_|
________________________________________
| version 1.0.5 - (c) 2016 Martin Ring |

[INFO] [06/23/2016 10:37:09.033] [scratch-akka.actor.default-dispatcher-3] [scratch] serving presentation from /Users/psp/scratch/cobra-scratch/scratch
[INFO] [06/23/2016 10:37:09.034] [scratch-akka.actor.default-dispatcher-3] [scratch] server is listening on localhost:8080
[INFO] [06/23/2016 10:37:10.300] [scratch-akka.actor.default-dispatcher-8] [scratch] initializing new scala document 'code_snippet_1'
[ERROR] [06/23/2016 10:37:15.677] [scratch-akka.actor.default-dispatcher-14] [akka.actor.LocalActorRefProvider(akka://scratch)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed: Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://www.assembla.com/spaces/scala-ide/support/tickets
    at scala.tools.nsc.interactive.Global.assertCorrectThread(Global.scala:537)
    at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1590)
    at scala.reflect.internal.Symbols$Symbol.signatureString(Symbols.scala:2676)
    at scala.reflect.internal.Symbols$Symbol.defString(Symbols.scala:2724)
    at scala.reflect.internal.TypeDebugging$$anonfun$typeParamsString$1.apply(TypeDebugging.scala:149)
    at scala.reflect.internal.TypeDebugging$$anonfun$typeParamsString$1.apply(TypeDebugging.scala:149)```
``````

**Comment by martinring** [comment]
Thank you for your report. Yes, to be honest, the Scala Integration is far from optimal right now. The development focussed mainly on Isabelle so far. I will look into this as soon as possible.

**Comment by martinring** [comment]
@paulp could you please provide an example of a *nontrivial piece of code*?

**Comment by paulp** [comment]
Sure.
```scala
package p {
  trait Functor[F[X]]   extends Any                      { def fmap[A, B](x: A => B): F[A] => F[B] }
  trait Pointed[F[X]]   extends Functor[F]               { def pure[A](x: A): F[A]                 }
  trait Monad[F[X]]     extends Pointed[F]               { def join[A](x: F[F[A]]): F[A]           }
  trait Copointed[F[X]] extends Functor[F]               { def copure[A](x: F[A]): A               }
  trait Comonad[F[X]]   extends Copointed[F]             { def cojoin[A](x: F[A]): F[F[A]]         }
  trait Bimonad[F[X]]   extends Monad[F] with Comonad[F]

  sealed trait Monadic[F[X], A]                                             extends Any
  final case class Pure[F[X], A](x: A)                                      extends Monadic[F, A]
  final case class Copure[F[X], A](x: F[A])                                 extends Monadic[F, A]
  final case class Map[F[X], A, B](prev: Monadic[F, A], f: A => B)          extends Monadic[F, B]
  final case class FlatMap[F[X], A, B](prev: Monadic[F, A], f: A => F[B])   extends Monadic[F, B]
  final case class CoflatMap[F[X], A, B](prev: Monadic[F, A], f: F[A] => B) extends Monadic[F, B]

  class MonadicInfix[F[X], A](prev: Monadic[F, A]) {
    def map[B](f: A => B): Monadic[F, B]          = Map(prev, f)
    def flatMap[B](f: A => F[B]): Monadic[F, B]   = FlatMap(prev, f)
    def coflatMap[B](f: F[A] => B): Monadic[F, B] = CoflatMap(prev, f)
    def run(implicit z: Bimonad[F]): A            = z copure resolve(prev)
  }
  object Test {
    implicit object ListMonad extends Bimonad[List] {
      def fmap[A, B](f: A => B)      = _ map f
      def join[A](xs: List[List[A]]) = xs.flatten
      def pure[A](x: A)              = List(x)
      def cojoin[A](xs: List[A])     = List(xs)
      def copure[A](x: List[A])      = x.head
    }
    def main(args: Array[String]): Unit = {
      val m = pure[List](10) flatMap (1 to _ toList) coflatMap (_.sum)
      println(m.run + " <- " + m)
      // output: 55 <- CoflatMap(FlatMap(Pure(10),<function1>),<function1>)
    }
  }
}
package object p {
  def pure[F[X]]                             = new { def apply[A](x: A): Pure[F, A] = Pure[F, A](x) }
  def copure[F[X], A](x: F[A]): Copure[F, A] = Copure(x)
  def resolve[F[X], A](x: Monadic[F, A])(implicit z: Bimonad[F]): F[A] = x match {
    case Pure(x)            => z pure x
    case Copure(x)          => x
    case Map(prev, f)       => resolve(prev) |> (z fmap f)
    case FlatMap(prev, f)   => resolve(prev) |> (z fmap f)   |> (z join _)
    case CoflatMap(prev, f) => resolve(prev) |> (z cojoin _) |> (z fmap f)
  }

  implicit def monadicInfix[F[X], A](x: Monadic[F, A]): MonadicInfix[F, A] = new MonadicInfix(x)
  implicit class ForwardPipe[A](x: A) { def |>[B](f: A => B): B = f(x) }
}
```
